# Generated by Django 3.2.8 on 2022-01-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20211228_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('dob', models.DateField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'User_type',
            },
        ),
    ]
