# Generated by Django 3.2.8 on 2022-01-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_type',
        ),
    ]
