# Generated by Django 3.2.8 on 2022-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='dob',
            field=models.DateField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
