# Generated by Django 3.2.8 on 2022-01-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_type_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='dob',
        ),
    ]
