# Generated by Django 3.2.8 on 2022-01-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_type_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='dob',
        ),
    ]
