# Generated by Django 3.2.8 on 2022-01-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_type_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='dob',
            field=models.DateField(max_length=15, null=True),
        ),
    ]
