# Generated by Django 3.2.8 on 2022-01-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_type_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='dob',
        ),
    ]
