# Generated by Django 3.2.8 on 2022-01-04 15:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0012_remove_user_type_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_type',
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
            ],
            options={
                'db_table': 'User_type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
