# Generated by Django 3.2.8 on 2022-01-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220104_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='last_login',
        ),
    ]
