# Generated by Django 3.2.8 on 2022-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AddField(
            model_name='user_type',
            name='is_enduser',
            field=models.BooleanField(default=False, verbose_name='Is enduser'),
        ),
        migrations.AddField(
            model_name='user_type',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Is moderator'),
        ),
    ]
