# Generated by Django 4.0.1 on 2022-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20220108_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, null=True)),
                ('product', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Req',
            },
        ),
    ]
