# Generated by Django 3.2.8 on 2022-01-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='id',
        ),
        migrations.AddField(
            model_name='user_type',
            name='role_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
