# Generated by Django 3.2.8 on 2022-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220115_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='role_id',
        ),
        migrations.AddField(
            model_name='user_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
