# Generated by Django 3.2.8 on 2022-01-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220115_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='req',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='req',
            name='product',
            field=models.CharField(max_length=20),
        ),
    ]
