# Generated by Django 3.2.8 on 2022-01-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220102_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_type',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
