# Generated by Django 3.2.8 on 2022-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220116_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
