# Generated by Django 3.2.8 on 2022-01-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_req_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
