# Generated by Django 3.2.8 on 2022-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20220117_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
