# Generated by Django 3.2.8 on 2022-01-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20220117_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
    ]
