# Generated by Django 3.2.8 on 2022-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_order_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_type',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='role',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
