# Generated by Django 3.2.8 on 2022-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20220117_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason',
            field=models.CharField(default='None', max_length=70),
            preserve_default=False,
        ),
    ]
