# Generated by Django 3.2.8 on 2022-01-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(choices=[('1', 'Has been ordered'), ('2', 'cooked'), ('3', 'ready to be served'), ('4', 'done')], max_length=70),
        ),
    ]
