# Generated by Django 3.2.8 on 2022-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(choices=[('Approved: Your requested has been approved', 'Approved: Your requested has been approved'), ('Rejected: Out of stock', 'Rejected: Out of stock'), ('Rejected: Unavailabilty of sufficient quantity', 'Rejected: Unavailabilty of sufficient quantity'), ('Rejected: reason 3', 'Rejected: reason 3')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
