# Generated by Django 3.2.8 on 2022-01-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20220118_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(blank=True, choices=[('Approved: Your requested has been approved', 'Approved: Your requested has been approved'), ('Rejected: Out of stock', 'Rejected: Out of stock'), ('Rejected: Unavailabilty of sufficient quantity', 'Rejected: Unavailabilty of sufficient quantity'), ('Rejected: reason 3', 'Rejected: reason 3')], max_length=120),
        ),
    ]
