# Generated by Django 3.2.8 on 2022-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reason',
            field=models.CharField(blank=True, choices=[('Approved: Your request has been approved', 'Approved: Your request has been approved'), ('Rejected: Out of stock', 'Rejected: Out of stock'), ('Rejected: Unavailabilty of sufficient quantity', 'Rejected: Unavailabilty of sufficient quantity'), ('Rejected: reason 3', 'Rejected: reason 3')], max_length=120),
        ),
    ]
