# Generated by Django 3.2.8 on 2022-01-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_type_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='role',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
