# Generated by Django 3.2.8 on 2022-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220104_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_type',
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('role', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'User_type',
            },
        ),
    ]
