# Generated by Django 3.2.8 on 2022-01-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220108_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_type',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='is_enduser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
