# Generated by Django 4.0.1 on 2022-01-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='category',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='req',
            name='product',
            field=models.CharField(max_length=10),
        ),
    ]
