# Generated by Django 3.2.8 on 2022-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('product', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
