# Generated by Django 4.0.1 on 2022-01-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_user_type_added_on_remove_user_type_upadte_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_type',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user_type',
            name='profile_pic',
        ),
    ]
